
project_id = "cwmzzdwoagtmxdmgtfzj"

[functions.fetch-wallet-data]
verify_jwt = true

[functions.send-telegram]
verify_jwt = true

[functions.send-email-summary]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.process-referral]
verify_jwt = false

[functions.satoai-chat]
verify_jwt = false

[functions.crypto-prices]
verify_jwt = false

[functions.tatum-wallet-api]
verify_jwt = true

[functions.crypto-wallet-manager]
verify_jwt = true

[functions.generate-crypto-wallets]
verify_jwt = true

[functions.secure-wallet-operations]
verify_jwt = true
